### ISSUE TITLE
[gitbase-web] chart only works if both external bblfshd and gitbase are present (or both absent)

### ISSUE THREAD

**Issue by smola** [src-d/charts#118]
The gitbase-web chart only works if both settings.gitbaseServer.address and settings.gitbaseServer.address are present or both are absent. Otherwise, both deployment.yaml and statefulset.yaml are empty.

Either both should work independently or this behavior should be clear in `values.yaml`

**Comment by meyskens** [comment]
Added into the values file and made Helm fail when this condition is not met.
https://github.com/src-d/charts/pull/126
