### ISSUE TITLE
Allow to specify driver versions for bblfsh in lookout chart

### ISSUE THREAD

**Issue by smacker** [src-d/charts#128]
Style-analyzer works only with specific version of js driver.
Issue: https://github.com/src-d/lookout/issues/413

I would propose the same solution as we did for bblfsh/web:
https://github.com/src-d/charts/tree/master/bblfsh-web
So we could do something like this: https://github.com/bblfsh/web/blob/master/.helm_staging.yml#L14 in lookout helm config.

**Comment by rporres** [comment]
Apologies for the late answer, I've somewhat missed this. Lookout chart implements the same bblfsh-sidecar container pattern that `bblfsh-web`, so you can specify those versions.

**Comment by smacker** [comment]
Cool thanks! It wasn't clear of lookout chart documentation.
