### ISSUE TITLE
[question] why is this a separate repo?

### ISSUE THREAD

**Issue by campoy** [src-d/charts#53]
I got here from the rovers repo, looking for an easy way to run it on kubernetes (thanks!)

It seems like this should simply be a directory under the rovers directory though.
So when more charts are added for other projects, say borges, then they can be easily added to their own repositories, where they're easier to find and maintain.

Is there a reason why this is not the case?

**Comment by rporres** [comment]
There are a number of reasons

* Helm charts are downloadable over https, it is normal to set up a charts repo that can be added locally (à la yum repository) and then download them from there. It is actually the usual way to use them
* Application code and packaging do not need to belong to the same repository
* We maintain charts that from repositories that don't belong to us
* We only maintain charts in the application repo whenever we're the only users of it (blog, landing, etc)

**Comment by campoy** [comment]
I'm tempted to ask you to document these reasons on the README.md

Actually, now that I think about it, this README.md does not follow the [documentation guidelines](https://github.com/src-d/guide/blob/master/engineering/documentation.md#readmemd).

**Comment by rporres** [comment]
Fair enough. I'll fix it ;-)
