### ISSUE TITLE
https://quay.io/srcd/spark-ui-proxy gives 403 unauthorized error

### ISSUE THREAD

**Issue by dcardamo** [src-d/charts#60]
When visiting https://quay.io/srcd/spark-ui-proxy I get a 403 unauthorized error.

**Comment by rporres** [comment]
From https://github.com/src-d/charts/pull/50 onwards I moved the images to dockerhub. You can find them in https://hub.docker.com/r/srcd/spark-ui-proxy/tags/

As you can see in https://github.com/src-d/spark-ui-proxy project has diverged a bit from upstream to make it work behind `kubectl proxy`
